/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ContentState = IDL.Record({
  'tagline' : IDL.Text,
  'ctaButtonText' : IDL.Text,
  'aboutText' : IDL.Text,
  'heroHeadline' : IDL.Text,
  'heroSubheading' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createService' : IDL.Func([Service], [IDL.Nat], []),
  'createTeamMember' : IDL.Func([TeamMember], [IDL.Nat], []),
  'deleteContactSubmission' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'deleteTeamMember' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getContent' : IDL.Func([], [ContentState], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getTeam' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([ContactSubmission], [IDL.Nat], []),
  'updateContent' : IDL.Func([ContentState], [], []),
  'updateService' : IDL.Func([Service], [], []),
  'updateTeamMember' : IDL.Func([TeamMember], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ContentState = IDL.Record({
    'tagline' : IDL.Text,
    'ctaButtonText' : IDL.Text,
    'aboutText' : IDL.Text,
    'heroHeadline' : IDL.Text,
    'heroSubheading' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createService' : IDL.Func([Service], [IDL.Nat], []),
    'createTeamMember' : IDL.Func([TeamMember], [IDL.Nat], []),
    'deleteContactSubmission' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'deleteTeamMember' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getContent' : IDL.Func([], [ContentState], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getTeam' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func([ContactSubmission], [IDL.Nat], []),
    'updateContent' : IDL.Func([ContentState], [], []),
    'updateService' : IDL.Func([Service], [], []),
    'updateTeamMember' : IDL.Func([TeamMember], [], []),
  });
};

export const init = ({ IDL }) => { return []; };